name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}-v4
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: |
        poetry install --no-interaction --with dev || poetry run pip install flake8==7.3.0 black==25.9.0 mypy==1.18.2

    - name: Debug Poetry environment
      run: |
        poetry env info
        poetry run pip list
        poetry run which flake8

    - name: Lint with flake8
      run: |
        poetry run flake8 guacapy --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 guacapy --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

    - name: Black
      run: |
        poetry run black --check --line-length=80 --diff guacapy